# Generated by Django 5.0.4 on 2024-08-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_organization', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_certificate_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_rating', models.FloatField(blank=True, max_length=1000, null=True)),
                ('course_reviews_num', models.IntegerField(blank=True, null=True)),
                ('course_difficulty', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('course_students_enrolled', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_skills', models.TextField(blank=True, max_length=1000, null=True)),
                ('course_summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
